### ISSUE TITLE
Test failure in DatasetVersionControllerTest

### ISSUE THREAD

**Issue by gthb** [diachron/archive#2]
Running `mvn clean install` as of now (commit b594187c77ba690bb6b8461a6b9b5eab25f79320), this test fails:

```
-------------------------------------------------------------------------------
Test set: org.athena.imis.diachron.archive.web.controllers.DatasetVersionControllerTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.025 sec <<< FAILURE!
testCreateDiachronicDatasetVersion(org.athena.imis.diachron.archive.web.controllers.DatasetVersionControllerTest)  Time elapsed: 0.014 sec  <<< FAILURE!
java.lang.AssertionError: data
Expected: testReply
     got: null

        at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:222)
        at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:192)
        at org.springframework.test.util.JsonExpectationsHelper.assertJsonEqual(JsonExpectationsHelper.java:42)
        at org.springframework.test.web.servlet.result.ContentResultMatchers$10.match(ContentResultMatchers.java:233)
        at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:152)
        at org.athena.imis.diachron.archive.web.controllers.DatasetVersionControllerTest.testCreateDiachronicDatasetVersion(DatasetVersionControllerTest.java:97)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:217)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
```

The test code that's failing is:

```java
            String contentValue = prepareContent(diachronicDatasetId);
            //MvcResult res =
        mockMvc.perform(MockMvcRequestBuilders.post("/archive/dataset/version")
                                .contentType(mediaType)
                                //.contentType("multipart/form-data")
                                .content(contentValue))
                                .andExpect(status().isOk())
                                .andExpect(jsonPath("$.success", is(true)))
                                .andExpect(content().json(jsonContent)).andReturn();
```

So the JSON being returned is not as expected. To inspect that JSON, I inserted a print action as follows:

```diff
diff --git a/diachron-archive/archive-web-services/src/test/java/org/athena/imis/diachron/archive/web/controllers/DatasetVersionControllerTest.java b/diachron-archive/archive-web-services/src/test/java/org/athena/imis/diachron/archive/web/controllers/Da
index d5d7a30..7e364f4 100644
--- a/diachron-archive/archive-web-services/src/test/java/org/athena/imis/diachron/archive/web/controllers/DatasetVersionControllerTest.java
+++ b/diachron-archive/archive-web-services/src/test/java/org/athena/imis/diachron/archive/web/controllers/DatasetVersionControllerTest.java
@@ -27,6 +27,7 @@ import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
 import org.springframework.test.context.web.WebAppConfiguration;
 import org.springframework.test.web.servlet.MockMvc;
 import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
+import org.springframework.test.web.servlet.result.MockMvcResultHandlers;
 import org.springframework.test.web.servlet.setup.MockMvcBuilders;
 import org.springframework.web.context.WebApplicationContext;
 
@@ -98,6 +99,7 @@ public class DatasetVersionControllerTest {
                                .contentType(mediaType)
                                //.contentType("multipart/form-data")
                                .content(contentValue))
+                               .andDo(MockMvcResultHandlers.print())
                                .andExpect(status().isOk())
                                .andExpect(jsonPath("$.success", is(true)))
                                .andExpect(content().json(jsonContent)).andReturn();
```

... and that shows the response contents:

```
MockHttpServletResponse:
              Status = 200
       Error message = null
             Headers = {Content-Type=[application/json;charset=UTF-8]}
        Content type = application/json;charset=UTF-8
                Body = {"message":"","data":null,"success":true}
       Forwarded URL = null
      Redirected URL = null
             Cookies = []
```

... and sure enough, that response body is not what should be emitted.

**Comment by pateritsas** [comment]
Fixed this in 7dcfea4c0a1744ccb4656b6845ccf00d20a74724
